-- =============================================
-- PORTAL DATABASE SCHEMA FOR SUPABASE
-- =============================================
-- This schema file represents the current state of the database
-- after all migrations have been applied. It uses BIGINT IDs for
-- most tables (except users and audit_logs which use UUID).

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- =============================================
-- USERS TABLE (extends Supabase auth.users)
-- =============================================
CREATE TABLE IF NOT EXISTS public.users (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'user' CHECK (role IN ('admin', 'moderator', 'muhasebe', 'user')),
  avatar_url TEXT,
  phone TEXT,
  role_id UUID REFERENCES public.roles(id) ON DELETE SET NULL,
  title VARCHAR,
  department VARCHAR,
  hire_date DATE,
  is_active BOOLEAN DEFAULT true,
  last_login TIMESTAMPTZ,
  created_by UUID REFERENCES public.users(id) ON DELETE SET NULL,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================
-- MEMBERS TABLE (Üyeler) - BIGINT ID
-- =============================================
CREATE TABLE IF NOT EXISTS public.members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tc_kimlik_no TEXT NOT NULL UNIQUE,
  ad TEXT NOT NULL,
  soyad TEXT NOT NULL,
  email TEXT,
  telefon TEXT NOT NULL CHECK (telefon ~ '^(0|\\+90)?5[0-9]{9}$'),
  cinsiyet TEXT NOT NULL CHECK (cinsiyet IN ('erkek', 'kadin')),
  dogum_tarihi DATE,
  adres TEXT,
  uye_turu TEXT NOT NULL DEFAULT 'standart' CHECK (uye_turu IN ('standart', 'onursal', 'fahri')),
  kayit_tarihi DATE NOT NULL DEFAULT CURRENT_DATE,
  aidat_durumu TEXT NOT NULL DEFAULT 'beklemede' CHECK (aidat_durumu IN ('odendi', 'beklemede', 'gecikti')),
  kan_grubu TEXT CHECK (kan_grubu IN ('A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', '0+', '0-')),
  meslegi TEXT,
  notlar TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================
-- DONATIONS TABLE (Bağışlar) - BIGINT ID
-- =============================================
CREATE TABLE IF NOT EXISTS public.donations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bagisci_adi TEXT NOT NULL,
  tutar DECIMAL(12, 2) NOT NULL,
  currency TEXT NOT NULL DEFAULT 'TRY' CHECK (currency IN ('TRY', 'USD', 'EUR')),
  amac TEXT NOT NULL,
  odeme_yontemi TEXT NOT NULL CHECK (odeme_yontemi IN ('nakit', 'havale', 'kredi_karti', 'kumbara')),
  makbuz_no TEXT,
  tarih DATE NOT NULL DEFAULT CURRENT_DATE,
  aciklama TEXT,
  member_id BIGINT REFERENCES public.members(id) ON DELETE SET NULL,
  bagisci_telefon TEXT,
  bagisci_email TEXT,
  bagisci_adres TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================
-- BENEFICIARIES TABLE (İhtiyaç Sahipleri) - BIGINT ID
-- =============================================
CREATE TABLE IF NOT EXISTS public.beneficiaries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tc_kimlik_no TEXT UNIQUE,
  ad TEXT NOT NULL,
  soyad TEXT NOT NULL,
  telefon TEXT NOT NULL,
  email TEXT,
  adres TEXT,
  il TEXT,
  ilce TEXT,
  cinsiyet TEXT NOT NULL CHECK (cinsiyet IN ('erkek', 'kadin')),
  dogum_tarihi DATE,
  medeni_hal TEXT,
  egitim_durumu TEXT,
  meslek TEXT,
  aylik_gelir DECIMAL(12, 2),
  hane_buyuklugu INTEGER,
  durum TEXT NOT NULL DEFAULT 'aktif' CHECK (durum IN ('aktif', 'pasif', 'arsiv', 'beklemede')),
  ihtiyac_durumu TEXT NOT NULL DEFAULT 'orta' CHECK (ihtiyac_durumu IN ('acil', 'yuksek', 'orta', 'dusuk')),
  kategori TEXT,
  parent_id BIGINT REFERENCES public.beneficiaries(id) ON DELETE SET NULL,
  relationship_type TEXT CHECK (relationship_type IN ('İhtiyaç Sahibi Kişi', 'Bakmakla Yükümlü Olunan Kişi')),
  uyruk TEXT DEFAULT 'Türkiye',
  yabanci_kimlik_no TEXT UNIQUE,
  fon_bolgesi TEXT,
  dosya_baglantisi TEXT,
  mernis_dogrulama BOOLEAN DEFAULT false,
  cep_telefonu TEXT,
  cep_telefonu_operator TEXT,
  sabit_telefon TEXT,
  yurtdisi_telefon TEXT,
  ulke TEXT DEFAULT 'Türkiye',
  sehir TEXT,
  mahalle TEXT,
  baba_adi TEXT,
  anne_adi TEXT,
  belge_turu TEXT,
  belge_gecerlilik_tarihi DATE,
  seri_numarasi TEXT,
  onceki_uyruk TEXT,
  onceki_isim TEXT,
  pasaport_turu TEXT,
  pasaport_numarasi TEXT,
  pasaport_gecerlilik_tarihi DATE,
  vize_giris_turu TEXT,
  vize_bitis_tarihi DATE,
  kan_grubu TEXT,
  kronik_hastalik TEXT,
  engel_durumu TEXT,
  engel_orani INTEGER CHECK (engel_orani >= 0 AND engel_orani <= 100),
  surekli_ilac TEXT,
  calisma_durumu TEXT,
  konut_durumu TEXT,
  kira_tutari DECIMAL(12, 2),
  es_adi TEXT,
  es_telefon TEXT,
  ailedeki_kisi_sayisi INTEGER,
  cocuk_sayisi INTEGER,
  yetim_sayisi INTEGER,
  calisan_sayisi INTEGER,
  bakmakla_yukumlu_sayisi INTEGER,
  sponsorluk_tipi TEXT CHECK (sponsorluk_tipi IN ('bireysel', 'kurumsal', 'yok')),
  riza_beyani_durumu TEXT CHECK (riza_beyani_durumu IN ('alinmadi', 'alindi', 'reddetti')),
  notlar TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================
-- KUMBARAS TABLE (Kumbaralar) - BIGINT ID
-- =============================================
CREATE TABLE IF NOT EXISTS public.kumbaras (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kod TEXT NOT NULL UNIQUE CHECK (length(kod) >= 3),
  konum TEXT NOT NULL CHECK (length(konum) >= 5),
  durum TEXT NOT NULL DEFAULT 'aktif' CHECK (durum IN ('aktif', 'pasif', 'toplandi', 'kayip')),
  sorumlu_id BIGINT REFERENCES public.members(id) ON DELETE SET NULL,
  son_toplama_tarihi TIMESTAMPTZ,
  toplam_toplanan DECIMAL(12, 2) NOT NULL DEFAULT 0,
  notlar TEXT CHECK (notlar IS NULL OR length(notlar) <= 500),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================
-- SOCIAL AID APPLICATIONS TABLE (Yardım Başvuruları) - BIGINT ID
-- =============================================
CREATE TABLE IF NOT EXISTS public.social_aid_applications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  basvuran_id BIGINT REFERENCES public.beneficiaries(id) ON DELETE CASCADE,
  yardim_turu TEXT NOT NULL CHECK (yardim_turu IN ('ayni', 'nakdi', 'egitim', 'saglik', 'kira', 'fatura')),
  talep_edilen_tutar DECIMAL(12, 2),
  onaylanan_tutar DECIMAL(12, 2),
  durum TEXT NOT NULL DEFAULT 'beklemede' CHECK (durum IN ('beklemede', 'inceleniyor', 'onaylandi', 'reddedildi')),
  basvuru_tarihi DATE NOT NULL DEFAULT CURRENT_DATE,
  degerlendirme_tarihi DATE,
  gerekce TEXT,
  basvuran_ad TEXT,
  basvuran_soyad TEXT,
  basvuran_tc_kimlik_no TEXT,
  basvuran_telefon TEXT,
  basvuran_adres TEXT,
  notlar TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================
-- PAYMENTS TABLE (Ödemeler) - BIGINT ID
-- =============================================
CREATE TABLE IF NOT EXISTS public.payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  application_id BIGINT NOT NULL REFERENCES public.social_aid_applications(id) ON DELETE CASCADE,
  beneficiary_id BIGINT NOT NULL REFERENCES public.beneficiaries(id) ON DELETE CASCADE,
  tutar DECIMAL(12, 2) NOT NULL,
  odeme_tarihi DATE NOT NULL DEFAULT CURRENT_DATE,
  odeme_yontemi TEXT NOT NULL CHECK (odeme_yontemi IN ('nakit', 'havale', 'elden')),
  durum TEXT NOT NULL DEFAULT 'beklemede' CHECK (durum IN ('beklemede', 'odendi', 'iptal')),
  makbuz_no TEXT,
  notlar TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================
-- DOCUMENTS TABLE (Dosya Metadata) - BIGINT ID
-- =============================================
CREATE TABLE IF NOT EXISTS public.documents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  beneficiary_id BIGINT REFERENCES public.beneficiaries(id) ON DELETE CASCADE,
  file_name TEXT NOT NULL,
  file_path TEXT NOT NULL,
  file_type TEXT NOT NULL CHECK (file_type IN ('application/pdf', 'image/jpeg', 'image/png', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document')),
  file_size INTEGER NOT NULL CHECK (file_size <= 10485760),
  document_type TEXT NOT NULL CHECK (document_type IN ('kimlik', 'ikamet', 'saglik', 'gelir', 'diger')),
  uploaded_by UUID REFERENCES public.users(id) ON DELETE SET NULL,
  mime_type TEXT,
  is_verified BOOLEAN DEFAULT false,
  verification_date TIMESTAMPTZ,
  verified_by UUID REFERENCES public.users(id) ON DELETE SET NULL,
  description TEXT,
  tags TEXT[],
  storage_bucket TEXT DEFAULT 'documents',
  storage_path TEXT,
  entity_type TEXT CHECK (entity_type IN ('beneficiary', 'member', 'application', 'payment', 'other')),
  entity_id BIGINT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================
-- AUDIT LOG TABLE - UUID ID, TEXT record_id
-- =============================================
CREATE TABLE IF NOT EXISTS public.audit_logs (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
  action TEXT NOT NULL,
  table_name TEXT NOT NULL,
  record_id TEXT,
  old_data JSONB,
  new_data JSONB,
  ip_address TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================
-- INDEXES
-- =============================================
CREATE INDEX IF NOT EXISTS idx_members_tc_kimlik ON public.members(tc_kimlik_no);
CREATE INDEX IF NOT EXISTS idx_members_ad_soyad ON public.members(ad, soyad);
CREATE INDEX IF NOT EXISTS idx_donations_tarih ON public.donations(tarih DESC);
CREATE INDEX IF NOT EXISTS idx_donations_amac ON public.donations(amac);
CREATE INDEX IF NOT EXISTS idx_beneficiaries_tc_kimlik ON public.beneficiaries(tc_kimlik_no);
CREATE INDEX IF NOT EXISTS idx_beneficiaries_durum ON public.beneficiaries(durum);
CREATE INDEX IF NOT EXISTS idx_beneficiaries_ihtiyac ON public.beneficiaries(ihtiyac_durumu);
CREATE INDEX IF NOT EXISTS idx_beneficiaries_parent_id ON public.beneficiaries(parent_id);
CREATE INDEX IF NOT EXISTS idx_beneficiaries_relationship_type ON public.beneficiaries(relationship_type);
CREATE INDEX IF NOT EXISTS idx_kumbaras_kod ON public.kumbaras(kod);
CREATE INDEX IF NOT EXISTS idx_kumbaras_durum ON public.kumbaras(durum);
CREATE INDEX IF NOT EXISTS idx_applications_durum ON public.social_aid_applications(durum);
CREATE INDEX IF NOT EXISTS idx_applications_basvuran ON public.social_aid_applications(basvuran_id);
CREATE INDEX IF NOT EXISTS idx_payments_beneficiary ON public.payments(beneficiary_id);
CREATE INDEX IF NOT EXISTS idx_documents_beneficiary ON public.documents(beneficiary_id);
CREATE INDEX IF NOT EXISTS idx_documents_type ON public.documents(document_type);
CREATE INDEX IF NOT EXISTS idx_documents_uploaded_by ON public.documents(uploaded_by);
CREATE INDEX IF NOT EXISTS idx_documents_created_at ON public.documents(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_user ON public.audit_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_audit_table ON public.audit_logs(table_name);
CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at ON public.audit_logs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_logs_action ON public.audit_logs(action);
CREATE INDEX IF NOT EXISTS idx_audit_logs_user_table ON public.audit_logs(user_id, table_name);
CREATE INDEX IF NOT EXISTS idx_audit_logs_record_id ON public.audit_logs(table_name, record_id);

-- =============================================
-- ROW LEVEL SECURITY (RLS)
-- =============================================
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.donations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.beneficiaries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.kumbaras ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.social_aid_applications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

-- =============================================
-- RLS POLICIES
-- =============================================
-- Note: Role-based RLS policies are defined in migration 20260113_add_role_based_rls_policies.sql
-- These are the basic policies that should exist. The role-based migration will replace
-- the simple authenticated policies with detailed role-based ones.

-- Users can view their own profile
CREATE POLICY "Users can view own profile" ON public.users
  FOR SELECT USING (auth.uid() = id);

-- Admins can view all users
CREATE POLICY "Admins can view all users" ON public.users
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM public.users WHERE id = auth.uid() AND role = 'admin'
    )
  );

-- Authenticated users can view members
CREATE POLICY "Authenticated users can view members" ON public.members
  FOR SELECT USING (auth.role() = 'authenticated');

-- Authenticated users can manage members
CREATE POLICY "Authenticated users can manage members" ON public.members
  FOR ALL USING (auth.role() = 'authenticated');

-- Authenticated users can view/manage donations
CREATE POLICY "Authenticated users can manage donations" ON public.donations
  FOR ALL USING (auth.role() = 'authenticated');

-- Authenticated users can view/manage beneficiaries
CREATE POLICY "Authenticated users can manage beneficiaries" ON public.beneficiaries
  FOR ALL USING (auth.role() = 'authenticated');

-- Authenticated users can view/manage kumbaras
CREATE POLICY "Authenticated users can manage kumbaras" ON public.kumbaras
  FOR ALL USING (auth.role() = 'authenticated');

-- Authenticated users can view/manage applications
CREATE POLICY "Authenticated users can manage applications" ON public.social_aid_applications
  FOR ALL USING (auth.role() = 'authenticated');

-- Authenticated users can view/manage payments
CREATE POLICY "Authenticated users can manage payments" ON public.payments
  FOR ALL USING (auth.role() = 'authenticated');

-- Authenticated users can view/manage documents
CREATE POLICY "Authenticated users can manage documents" ON public.documents
  FOR ALL USING (auth.role() = 'authenticated');

-- Only admins can view audit logs
CREATE POLICY "Admins can view audit logs" ON public.audit_logs
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM public.users WHERE id = auth.uid() AND role = 'admin'
    )
  );

-- =============================================
-- FUNCTIONS & TRIGGERS
-- =============================================

-- Function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Triggers for updated_at
CREATE TRIGGER update_users_updated_at
  BEFORE UPDATE ON public.users
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER update_members_updated_at
  BEFORE UPDATE ON public.members
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER update_beneficiaries_updated_at
  BEFORE UPDATE ON public.beneficiaries
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER update_kumbaras_updated_at
  BEFORE UPDATE ON public.kumbaras
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER update_applications_updated_at
  BEFORE UPDATE ON public.social_aid_applications
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- Function to create user profile on signup
CREATE OR REPLACE FUNCTION handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.users (id, email, name, role)
  VALUES (
    NEW.id,
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'name', split_part(NEW.email, '@', 1)),
    'user'
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger for new user signup
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION handle_new_user();
