-- =============================================
-- SEED DATA FOR DEVELOPMENT
-- =============================================
-- This file is kept for reference but contains no demo/test data.
-- Add your own seed data here if needed for development.
-- 
-- Usage: Run this in Supabase SQL Editor or via CLI
-- supabase db reset (will run seed.sql automatically if configured)

-- =============================================
-- CLEAR EXISTING DATA (Optional - uncomment if needed)
-- =============================================
-- TRUNCATE TABLE public.payments CASCADE;
-- TRUNCATE TABLE public.social_aid_applications CASCADE;
-- TRUNCATE TABLE public.documents CASCADE;
-- TRUNCATE TABLE public.kumbaras CASCADE;
-- TRUNCATE TABLE public.donations CASCADE;
-- TRUNCATE TABLE public.beneficiaries CASCADE;
-- TRUNCATE TABLE public.members CASCADE;

-- Add your seed data below if needed
